// gen-model-paths: generates the gNMI model path registry C table from
// a JSON spec derived from the YANG models (openconfig-interfaces first).
//
// Usage: gen-model-paths <spec.json> <out .inc>
//
// Spec entry:
//   { "path": "/interfaces/interface[name]/config/mtu",
//     "kind": "leaf",          // list | entry | leaf
//     "obj":  "iface",         // iface | vrf | route
//     "field": "mtu" }         // mtu | enabled | name | link-up | none
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

type entry struct {
	Path  string `json:"path"`
	Kind  string `json:"kind"`
	Obj   string `json:"obj"`
	Field string `json:"field"`
}

func ckind(k string) string {
	switch k {
	case "list":
		return "GNMI_MODEL_LIST"
	case "entry":
		return "GNMI_MODEL_ENTRY"
	default:
		return "GNMI_MODEL_LEAF"
	}
}

func cobj(o string) string {
	switch o {
	case "iface":
		return "DANOS_OBJ_IFACE"
	case "vrf":
		return "DANOS_OBJ_VRF"
	default:
		return "DANOS_OBJ_ROUTE"
	}
}

func cfield(f string) string {
	switch f {
	case "mtu":
		return "GNMI_FIELD_MTU"
	case "enabled":
		return "GNMI_FIELD_ENABLED"
	case "name":
		return "GNMI_FIELD_NAME"
	case "link-up":
		return "GNMI_FIELD_LINK_UP"
	default:
		return "GNMI_FIELD_NONE"
	}
}

/* The generated matcher compares the path against the spec pattern:
 * "[name]" matches any keyed element, literal text matches exactly. */
func genMatcher(e entry, idx int) string {
	var b strings.Builder
	segs := strings.Split(strings.Trim(e.Path, "/"), "/")
	fmt.Fprintf(&b, "    /* %s */\n", e.Path)
	fmt.Fprintf(&b, "    if (p->elem_count == %d", len(segs))
	for i, seg := range segs {
		if strings.HasSuffix(seg, "]") {
			name := strings.TrimSuffix(seg, "[")
			if !strings.Contains(seg, "[") { // bare key element
				fmt.Fprintf(&b, " &&\n        strcmp(p->elems[%d].name, \"%s\") == 0 && p->elems[%d].has_key", i, name, i)
				continue
			}
			// form name[key]
			fmt.Fprintf(&b, " &&\n        strcmp(p->elems[%d].name, \"%s\") == 0 && p->elems[%d].has_key", i, name, i)
			continue
		}
		fmt.Fprintf(&b, " &&\n        strcmp(p->elems[%d].name, \"%s\") == 0", i, seg)
	}
	fmt.Fprintf(&b, ") {\n")
	fmt.Fprintf(&b, "        b->kind = %s;\n        b->obj_type = %s;\n        b->field = %s;\n", ckind(e.Kind), cobj(e.Obj), cfield(e.Field))
	fmt.Fprintf(&b, "        b->config_tree = has_config_segment(p);\n")
	fmt.Fprintf(&b, "        return DANOS_OK;\n    }\n")
	_ = idx
	return b.String()
}

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintln(os.Stderr, "usage: gen-model-paths <spec.json> <out.inc>")
		os.Exit(2)
	}
	data, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var entries []entry
	if err := json.Unmarshal(data, &entries); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	out, err := os.Create(os.Args[2])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer out.Close()
	fmt.Fprintln(out, "/* GENERATED by tools/gen-model-paths from model_paths.json — do not edit */")
	fmt.Fprintln(out, "/* Generated-matcher entries are consulted before the hand-written */")
	fmt.Fprintln(out, "/* fallback in model_paths.c resolve().                            */")
	for _, e := range entries {
		out.WriteString(genMatcher(e, 0))
	}
	fmt.Fprintf(os.Stderr, "generated %d path bindings\n", len(entries))
}
